### ISSUE TITLE
Hitting enter e.g. when adding new subcorpus gives unpexpected behavior

### ISSUE THREAD

**Issue by apohllo** [CLARIN-PL/Inforex#71]
When the pop up for creating new subcorpus is opened, one would expect "enter" to create the subcorpus. But the key moves the user to a different sub-page and the subcorpus is not created...
Changing the behavior would be much appreciated.

**Comment by apohllo** [comment]
Just to make the issue more informative - it only happens when the focus is on the name of the subcorpus.

**Comment by tnaskret** [comment]
expired
