### ISSUE TITLE
Allow for displaying document flags in "browse documents"

### ISSUE THREAD

**Issue by apohllo** [CLARIN-PL/Inforex#72]
It would be very helpful, if the table allowed for displaying the flag assigned to the documents.
At present, I have to guess what is the document's flag.

**Comment by mczuk** [comment]
Do you mean this https://youtu.be/vOXvudtD00E or something else?

**Comment by apohllo** [comment]
Well, some of the labels could be more informative (I mean `F:` is a bit cryptic and there is no tooltip for that). Thanks for sharing the video!
