### ISSUE TITLE
Pane collaps/size change

### ISSUE THREAD

**Issue by apohllo** [CLARIN-PL/Inforex#87]
When working in "agreement/relation agreement" perspective, most of the time the user is interested only in the first two panes: resolve annotations and document content. The view configuration is only important at the beginning. Since it is open all the time, it limits the space available for the first two panes. 

It would be good if:
- it was possible to collapse the "view configuration" pane or
- resize the panes by hand.

**Comment by mczuk** [comment]
It is already possible by clicking the gear icon. It will close the "View configuration" panel. 

![image](https://user-images.githubusercontent.com/35594390/77420458-5bd92400-6dca-11ea-8340-5f2e4c8076da.png)

After clicking: 
![image](https://user-images.githubusercontent.com/35594390/77420510-757a6b80-6dca-11ea-8bf9-cd4b98028a97.png)


![image](https://user-images.githubusercontent.com/35594390/77420486-6a274000-6dca-11ea-98eb-e9c1148798b9.png)

**Comment by apohllo** [comment]
Ok, thanks for the tip. I'm closing.

**Comment by apohllo** [comment]
As a note - my last change in GUI might have broken a bit this feature. When the config is collapsed there is some space on the left side left.
