### ISSUE TITLE
Annotation of tokens is absent if they span more than one sentence

### ISSUE THREAD

**Issue by apohllo** [CLARIN-PL/Inforex#90]
We have a use case when one annotation spans more than one sentence. Unfortunately it seems that when the annotation is exported, only the tokens present in the first sentence of the span get their annotations. We would expect that all tokens in all sentences in the same annotation span will have the same annotation id.

**Comment by mczuk** [comment]
Could you suggested what might be the expected behavior? I see the following solutions:
1. The annotation is split between sentences.
2. The sentences are merged into a single sentence.

**Comment by apohllo** [comment]
For our use case the second solution works much better. We have to annotate long blocks of texts and the fact that they are atomic is pretty important.

**Comment by tnaskret** [comment]
expired
